name: concurrency and timeout

on: 
    # workflow_ dispatch explain how job need to trigger eg: webhook
#  workflow_dispatch:  
#  schedule:
#    - cron: "15 4,5 * * *"   # <=== Change this value
  push:

jobs:

  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Docker Build
        env: 
          CONTAINER_REGISTRY: docker.io
          DOCKER_USERNAME: thanusn308@gmail.com
          IMAGE_NAME: github-actions-nginx
        run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest .

      - name: Docker Login
        env:
          DOCKER_USERNAME: thanusn308@gmail.com
          DOCKER_PASSWORD: Thanu1235
        run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

      - name: Docker Publish
        env:
          CONTAINER_REGISTRY: docker.io
          DOCKER_USERNAME: thanusn308@gmail.com
          IMAGE_NAME: github-actions-nginx
        run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

  Deployment-job:
    timeout-minutes: 2
    needs: docker
    concurrency:
      group: production deployment
      cancel-in-progress: false 
    runs-on: ubuntu-latest
    steps:
      - name: concurrency 
        timeout-minutes: 1
        run: echo Deploying... and checking cuncurrency and timeout for job oo stpes to complete
      
      - name: using sleep
        timeout-minutes: 2
        run : sleep 600s 







































 

       



 
 

