name: ascii installation

on: push

jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Installing cowsay
        run: sudo apt-get install cowsay -y

      - name: Execute cowsay command
        run: cowsay -f dragon "Run from cover, I am a dragon......rawr" >> dragon.txt

      - name: Show file content
        run: cat dragon.txt

      - name: Check if sample.sh exists
        run: ls -a .github/workflows/

      - name: Run shell script
        run: |
         chmod +x ./github/workflows/sample.sh
         ./github/workflows/sample.sh


