name: Exploring Secrets

on:
  push:

# Need add variables and secrets in github settings
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Build
        run: echo docker build -t ${{ env.CONTAINER_REGISTRY }}/$DOCKER_USERNAME/$IMAGE_NAME:latest .

      - name: Docker Login
 
        run: |
          echo  
          echo docker login --username=$DOCKER_USERNAME --password=${{ secrets.DOCKER_PASSWORD }} 

      - name: Docker Publish
        run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

