name: upload-dowload

on: 
   push

jobs: 
    build_job1:
      runs-on: ubuntu-latest
      steps:
      - name: Installing cowsay
        run: sudo apt-get install cowsay -y

      - name: Execute cowsay command
        run: cowsay -f dragon "Run from cover, I am a dragon......rawr" >> dragon.txt

      - name: Show file content
        run: cat dragon.txt

      - name: Show file content  
        uses: actions/upload-artifact@v4
        with: 
          name: uploading dragon
          path: dragon.txt


    test_job2:
      needs: build_job1
      runs-on: ubuntu-latest
      steps:
        - name: dowloading dragon.txt
          uses: actions/download-artifact@v4
          with: 
             name: uploading dragon
        
        - name: checking dragon
          run: grep -i "dragon" dragon.txt
      
    deploy_job3:
      needs: [build_job1, test_job2]
      runs-on: ubuntu-latest
      steps:
        - name: dowloading dragon.txt
          uses: actions/download-artifact@v4
          with: 
             name: uploading dragon

        - name: Show file content
          run: cat dragon.txt

        - name: Deploy
          run: echo "Deploying...."






