name: Exploring variables

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
          CONTAINER_REGISTRY: docker.io
          DOCKER_USERNAME: thanusn308@gmail.com
          IMAGE_NAME: github-actions-nginx
    steps:
      - name: Docker Build
        run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest .

      - name: Docker Login
        env: 
          DOCKER_PASSWORD: Thanu1235
        run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

      - name: Docker Publish 
        run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest



 
 

